name: augmented_intelligence
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - websockets
      - openai
      - requests
      - Pillow
      - wordcloud
      - matplotlib
      - pyaudio
      - assemblyai
      - PyYAML
      - pillow
      - keyboard
